/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIUBER;

import UberCarManagement.CarDetails;
import javax.swing.JPanel;
import UberCarManagement.UberCar;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sreyoshighosh
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    private JPanel usrprocessconta;
    private CarDetails carlistinfor;
    private ArrayList<String> brands;
    //private int manufactured_year;
       
       
    SearchJPanel(JPanel usrpro, CarDetails infolistcar) {
        initComponents();
        this.usrprocessconta=usrpro;
        this.carlistinfor= infolistcar;
      //  this.manufactured_year=manufactured_year;
        populateTable();    
    }
    
 private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel(); 
        dtm.setRowCount(0);
        for (UberCar car : carlistinfor.getSelectcar()){
            Object[] row = new Object[10];
            row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
            brands= new ArrayList<>();
            brands.add(car.getBrand());
    }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldisplay = new javax.swing.JTable();
        pnlcolorpurple = new javax.swing.JPanel();
        pnlcolorblack = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblyear = new javax.swing.JLabel();
        lblbrand = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnMfgDate = new javax.swing.JButton();
        lblcity = new javax.swing.JLabel();
        txtbrand2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        btnBrand = new javax.swing.JButton();
        btnCity = new javax.swing.JButton();
        lblmodelno = new javax.swing.JLabel();
        btnSerialNumber = new javax.swing.JButton();
        lblmaxseat = new javax.swing.JLabel();
        lblminseat = new javax.swing.JLabel();
        txtMxseat = new javax.swing.JTextField();
        txtMnseat = new javax.swing.JTextField();
        btnMaxMin = new javax.swing.JButton();
        txtModno = new javax.swing.JTextField();
        lblserialnumber = new javax.swing.JLabel();
        txtSrno = new javax.swing.JTextField();
        btnModelNumber = new javax.swing.JButton();
        btnExpiredCertificate = new javax.swing.JButton();
        btnManufacturing = new javax.swing.JButton();
        btngoback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tbldisplay.setBackground(new java.awt.Color(204, 255, 204));
        tbldisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model no", "Min Seat", "Max Seat", "Serial Number", "Manufacturing Year", "Available in City", "Maintainance Certificate", "Available for UBER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldisplay);

        pnlcolorpurple.setBackground(new java.awt.Color(153, 0, 255));

        pnlcolorblack.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("FIND YOUR CONVENIENT CAR");

        javax.swing.GroupLayout pnlcolorblackLayout = new javax.swing.GroupLayout(pnlcolorblack);
        pnlcolorblack.setLayout(pnlcolorblackLayout);
        pnlcolorblackLayout.setHorizontalGroup(
            pnlcolorblackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcolorblackLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        pnlcolorblackLayout.setVerticalGroup(
            pnlcolorblackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcolorblackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlcolorpurpleLayout = new javax.swing.GroupLayout(pnlcolorpurple);
        pnlcolorpurple.setLayout(pnlcolorpurpleLayout);
        pnlcolorpurpleLayout.setHorizontalGroup(
            pnlcolorpurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcolorpurpleLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(pnlcolorblack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlcolorpurpleLayout.setVerticalGroup(
            pnlcolorpurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcolorpurpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlcolorblack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        lblyear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblyear.setForeground(new java.awt.Color(0, 255, 0));
        lblyear.setText("Year:");

        lblbrand.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblbrand.setForeground(new java.awt.Color(0, 255, 0));
        lblbrand.setText("Brand:");

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        btnMfgDate.setBackground(new java.awt.Color(255, 255, 153));
        btnMfgDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMfgDate.setText("Search");
        btnMfgDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMfgDateActionPerformed(evt);
            }
        });

        lblcity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblcity.setForeground(new java.awt.Color(0, 255, 0));
        lblcity.setText("City:");

        txtbrand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrand2ActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        btnBrand.setBackground(new java.awt.Color(255, 255, 153));
        btnBrand.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBrand.setText("Search");
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        btnCity.setBackground(new java.awt.Color(255, 255, 153));
        btnCity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCity.setText("Search");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });

        lblmodelno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblmodelno.setForeground(new java.awt.Color(0, 255, 0));
        lblmodelno.setText("Model No:");

        btnSerialNumber.setBackground(new java.awt.Color(255, 255, 153));
        btnSerialNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSerialNumber.setText("Search");
        btnSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumberActionPerformed(evt);
            }
        });

        lblmaxseat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblmaxseat.setForeground(new java.awt.Color(0, 255, 0));
        lblmaxseat.setText("Max Seat:");

        lblminseat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblminseat.setForeground(new java.awt.Color(0, 255, 0));
        lblminseat.setText("Min Seat:");

        txtMxseat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMxseatActionPerformed(evt);
            }
        });

        btnMaxMin.setBackground(new java.awt.Color(255, 255, 153));
        btnMaxMin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMaxMin.setText("Search");
        btnMaxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxMinActionPerformed(evt);
            }
        });

        txtModno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModnoActionPerformed(evt);
            }
        });

        lblserialnumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblserialnumber.setForeground(new java.awt.Color(0, 255, 51));
        lblserialnumber.setText("Serial Number:");

        txtSrno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSrnoActionPerformed(evt);
            }
        });

        btnModelNumber.setBackground(new java.awt.Color(255, 255, 153));
        btnModelNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnModelNumber.setText("Search");
        btnModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNumberActionPerformed(evt);
            }
        });

        btnExpiredCertificate.setBackground(new java.awt.Color(255, 255, 153));
        btnExpiredCertificate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExpiredCertificate.setText("Expired Certificate");
        btnExpiredCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredCertificateActionPerformed(evt);
            }
        });

        btnManufacturing.setBackground(new java.awt.Color(255, 255, 153));
        btnManufacturing.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManufacturing.setText("Manufactured Co.");
        btnManufacturing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturingActionPerformed(evt);
            }
        });

        btngoback.setBackground(new java.awt.Color(255, 255, 153));
        btngoback.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btngoback.setText("<<GO BACK");
        btngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngobackActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbrand)
                            .addComponent(lblcity)
                            .addComponent(lblyear))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblserialnumber)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtbrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCity)
                                        .addComponent(btnBrand)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnMfgDate))))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblmodelno)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblminseat)
                                .addComponent(lblmaxseat)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMnseat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMxseat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtModno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMaxMin)
                                    .addComponent(btnModelNumber)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExpiredCertificate)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(txtSrno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnSerialNumber))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btngoback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbrand)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmodelno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModelNumber))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbrand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrand)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCity)
                    .addComponent(lblmaxseat)
                    .addComponent(txtMxseat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(btnMaxMin)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblyear)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMfgDate)
                            .addComponent(lblminseat)
                            .addComponent(txtMnseat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblserialnumber)
                            .addComponent(txtSrno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSerialNumber))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btngoback, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExpiredCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlcolorpurple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlcolorpurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMfgDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMfgDateActionPerformed
      
        try{
        int manufactured_year = (Integer.parseInt(txtYear.getText()));
        ArrayList<UberCar> result = carlistinfor.getmanufacturelist(manufactured_year);                
        if (result==null){
            JOptionPane.showMessageDialog(null, "Enter the correct format of Year");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : result){
           Object[] row = new Object[10];
            row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
     }
    }//GEN-LAST:event_btnMfgDateActionPerformed
        }catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Enter the correct format of Year");
        }
        }        
                
    private void btnSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumberActionPerformed
        // TODO add your handling code here:
        
        try{
        int serial_num = (Integer.parseInt(txtSrno.getText()));
        ArrayList<UberCar> resultNew = carlistinfor.getsrlist(serial_num);
        if (resultNew==null){
            JOptionPane.showMessageDialog(null, "Enter correct Serial Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : resultNew){
            Object[] row = new Object[10];
            row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
     }
    }             
        }
catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "Invalid Number");}  
    }//GEN-LAST:event_btnSerialNumberActionPerformed

    private void txtSrnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSrnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSrnoActionPerformed

    private void txtbrand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrand2ActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        String brand = txtbrand2.getText();
        ArrayList<UberCar> result = carlistinfor.getbrndlist(brand);        
        if (result==null){
            JOptionPane.showMessageDialog(null, "Enter correct Brand");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : result){
           Object[] row = new Object[10];
           row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
     }
    }             
    }//GEN-LAST:event_btnBrandActionPerformed

    private void txtModnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModnoActionPerformed
         // TODO add your handling code here:
//        String model_num = txtModno.getText();
//        ArrayList<UberCar> resultNew = carlistinfor.getmodel(model_num);        
//          if (resultNew.equals("")){
//            JOptionPane.showMessageDialog(null, "Enter correct Model Number");
//        }
//        else {
//      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
//       dtm.setRowCount(0);
//       for(UberCar car : resultNew){
//           Object[] row = new Object[10];
//           row[0] = car;
//            row[1] = car.getManufacture();
//            row[2]= car.getMaxseats();
//            row[3]= car.getMinseats();
//            row[4]=car.getSrnumber();
//            row[5]=car.getModnumber();
//            row[6]=car.getCityAvailable();
//            row[7]=car.isAvailable();
//            row[8]=car.isMaintcert();
//            row[9]=car.getUpdatedOn();
//            dtm.addRow(row);
//     }
//    }                                             
//
    }//GEN-LAST:event_txtModnoActionPerformed

    private void btnModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNumberActionPerformed
        // TODO add your handling code here:
        String model_num = txtModno.getText();
        ArrayList<UberCar> resultNew = carlistinfor.getmodel(model_num);        
          if (resultNew.equals("")){
            JOptionPane.showMessageDialog(null, "Enter correct Model Number");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : resultNew){
           Object[] row = new Object[10];
            row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
     }
    } 
    }//GEN-LAST:event_btnModelNumberActionPerformed

    private void btnExpiredCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredCertificateActionPerformed
        // TODO add your handling code here:
         ArrayList<UberCar> resultNew = carlistinfor.getmntcertif();
        
          if (resultNew==null){
            JOptionPane.showMessageDialog(null, "Expired Certificate entry is invalid");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : resultNew){
           Object[] row = new Object[10];
           row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
     }
    }         
    }//GEN-LAST:event_btnExpiredCertificateActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        // TODO add your handling code here:
         String availble_city = txtCity.getText();
        ArrayList<UberCar> resultNew = carlistinfor.getAvailCars(availble_city);        
          if (resultNew==null){
            JOptionPane.showMessageDialog(null, "Invalid city entry.");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : resultNew){
           Object[] row = new Object[10];
            row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();            
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);
     }
    }                 
    }//GEN-LAST:event_btnCityActionPerformed

    private void btnMaxMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxMinActionPerformed
        // TODO add your handling code here:
        try{        
        int max_seats = (Integer.parseInt(txtMxseat.getText()));
        int min_seats = (Integer.parseInt(txtMnseat.getText()));
        ArrayList<UberCar> resultNew = carlistinfor.getmaxindetail(max_seats, min_seats);                
            if (resultNew==null){
            JOptionPane.showMessageDialog(null, "seat no is not correct");
        }
        else {
      DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for(UberCar car : resultNew){
           Object[] row = new Object[10];
           row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);                        
     }
 if (min_seats == 1) {
                JOptionPane.showMessageDialog(null, "Min Seat has to be more than 0");
return;
            }

            if (max_seats > 20) {
                JOptionPane.showMessageDialog(null, "Max Seat has to be less than 20");
return;
            }
if (min_seats>max_seats){
JOptionPane.showMessageDialog(null, "Min can not be greater than max");
return;
}
//if(min_seats=max_seats){
//JOptionPane.showMessageDialog(null, "Min can not be greater than max");
//return;
//}
//if(txtMxseat<=max_seats){
//JOptionPane.showMessageDialog(null, "Min can not be greater than max");
//
//}
            }     
        }
catch(NumberFormatException c){JOptionPane.showMessageDialog(null, "Enter the correct entry");} 
    }//GEN-LAST:event_btnMaxMinActionPerformed

    private void btnManufacturingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturingActionPerformed
        // TODO add your handling code here:        
        ArrayList<String> car = carlistinfor.getall();
        Set<String> setString = new HashSet<String>(car);
        ArrayList<String> finalList = new ArrayList<>(setString);                
        DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel();
       dtm.setRowCount(0);
       for (String c : finalList)
       {
       Object[] row = new Object [10];
       row[0]=c;
       dtm.addRow(row);       
       }        
    }//GEN-LAST:event_btnManufacturingActionPerformed

    private void btngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngobackActionPerformed
        // TODO add your handling code here:        
        usrprocessconta.remove(this);
           CardLayout layout = (CardLayout) usrprocessconta.getLayout();
           layout.previous(usrprocessconta);
    }//GEN-LAST:event_btngobackActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtMxseatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMxseatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMxseatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnExpiredCertificate;
    private javax.swing.JButton btnManufacturing;
    private javax.swing.JButton btnMaxMin;
    private javax.swing.JButton btnMfgDate;
    private javax.swing.JButton btnModelNumber;
    private javax.swing.JButton btnSerialNumber;
    private javax.swing.JButton btngoback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbrand;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblmaxseat;
    private javax.swing.JLabel lblminseat;
    private javax.swing.JLabel lblmodelno;
    private javax.swing.JLabel lblserialnumber;
    private javax.swing.JLabel lblyear;
    private javax.swing.JPanel pnlcolorblack;
    private javax.swing.JPanel pnlcolorpurple;
    private javax.swing.JTable tbldisplay;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMnseat;
    private javax.swing.JTextField txtModno;
    private javax.swing.JTextField txtMxseat;
    private javax.swing.JTextField txtSrno;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtbrand2;
    // End of variables declaration//GEN-END:variables
}
