/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIUBER;
import UberCarManagement.UberCar;
import UberCarManagement.CarDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;
import java.sql.Timestamp;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sreyoshighosh
 */
public class UpdateJPanel extends javax.swing.JPanel {

    private JPanel ProcCont;
    private CarDetails carinlist;
    private UberCar c;    
    private Date date;
    private Timestamp timestamp;    
    public static String Time;
    public static String getTime() {
        return Time;
    }
    public static void setTime(String Time) {
        UpdateJPanel.Time = Time;
    }
   
    public UpdateJPanel(JPanel userContProc, CarDetails carLinfo) {
        initComponents();
        this.ProcCont=userContProc;
       this.carinlist=carLinfo;       
       populateTable();                          
    }    
    
    private void populateCarDetails(){
       
        int selectedrow =tbldisplay.getSelectedRow();
        c = (UberCar) tbldisplay.getValueAt(selectedrow, 0);                        
        txtYmanufact.setText(String.valueOf(c.getManufacture()));
        txtbrand2.setText(c.getBrand());
        txtcity.setText(c.getCityAvailable());
        txtmxseat.setText(String.valueOf(c.getMaxseats()));
        txtmnseat.setText(String.valueOf(c.getMinseats()));
        txtmodno.setText(c.getModnumber());
        txtserailrnum.setText(String.valueOf(c.getSrnumber()));
        if(c.isAvailable()==true)
            rbYesAvailability.setSelected(true);        
        else
            rbNoAvailability.setSelected(true);
        
        if(c.isMaintcert()==true)
            rbYesMaintainance.setSelected(true);
        else
            rbNoMaintainance.setSelected(true);                
    }
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbldisplay.getModel(); 
        dtm.setRowCount(0);
        for (UberCar car : carinlist.getSelectcar()){
            Object[] row = new Object[10];
            row[0] = car;
            row[1]=car.getModnumber();            
            row[2]= car.getMinseats();
            row[3]= car.getMaxseats();
            row[4]=car.getSrnumber();
            row[5] = car.getManufacture();
            row[6]=car.getCityAvailable();
            row[7]=car.isMaintcert();
            row[8]=car.isAvailable();
            row[9]=car.getUpdatedOn();
            dtm.addRow(row);            
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldisplay = new javax.swing.JTable();
        lblTime = new javax.swing.JLabel();
        pnlcolor1 = new javax.swing.JPanel();
        pnlcolor2 = new javax.swing.JPanel();
        lblred = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtbrand2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmodno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmnseat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmxseat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtserailrnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtYmanufact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rbYesMaintainance = new javax.swing.JRadioButton();
        rbNoMaintainance = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rbYesAvailability = new javax.swing.JRadioButton();
        rbNoAvailability = new javax.swing.JRadioButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btngoback = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tbldisplay.setBackground(new java.awt.Color(204, 255, 204));
        tbldisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model No", "Min Seat", "Max Seat", "Serial Number", "Manufacture Year", "Available in City", "Maintainance Certificate", "Available for UBER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldisplay);

        pnlcolor1.setBackground(new java.awt.Color(153, 0, 255));

        pnlcolor2.setBackground(new java.awt.Color(0, 0, 0));

        lblred.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblred.setForeground(new java.awt.Color(255, 0, 0));
        lblred.setText("UPDATE YOUR CAR DETAILS");

        javax.swing.GroupLayout pnlcolor2Layout = new javax.swing.GroupLayout(pnlcolor2);
        pnlcolor2.setLayout(pnlcolor2Layout);
        pnlcolor2Layout.setHorizontalGroup(
            pnlcolor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcolor2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(lblred)
                .addGap(116, 116, 116))
        );
        pnlcolor2Layout.setVerticalGroup(
            pnlcolor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcolor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblred, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout pnlcolor1Layout = new javax.swing.GroupLayout(pnlcolor1);
        pnlcolor1.setLayout(pnlcolor1Layout);
        pnlcolor1Layout.setHorizontalGroup(
            pnlcolor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcolor1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pnlcolor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlcolor1Layout.setVerticalGroup(
            pnlcolor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcolor1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlcolor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Brand:");

        txtbrand2.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Model No:");

        txtmodno.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Min Seat:");

        txtmnseat.setEnabled(false);
        txtmnseat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnseatActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 0));
        jLabel6.setText("Max Seat:");

        txtmxseat.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("Serial Number:");

        txtserailrnum.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Year of Manufacture:");

        txtYmanufact.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 0));
        jLabel9.setText("City:");

        txtcity.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 0));
        jLabel10.setText("Maintainance Certificate:");

        buttonGroup1.add(rbYesMaintainance);
        rbYesMaintainance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbYesMaintainance.setForeground(new java.awt.Color(0, 51, 255));
        rbYesMaintainance.setText("Yes");
        rbYesMaintainance.setEnabled(false);
        rbYesMaintainance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYesMaintainanceActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNoMaintainance);
        rbNoMaintainance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbNoMaintainance.setForeground(new java.awt.Color(0, 51, 255));
        rbNoMaintainance.setText("No");
        rbNoMaintainance.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("Availability for UBER:");

        buttonGroup2.add(rbYesAvailability);
        rbYesAvailability.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbYesAvailability.setForeground(new java.awt.Color(0, 51, 255));
        rbYesAvailability.setText("Yes");
        rbYesAvailability.setEnabled(false);

        buttonGroup2.add(rbNoAvailability);
        rbNoAvailability.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbNoAvailability.setForeground(new java.awt.Color(0, 51, 255));
        rbNoAvailability.setText("No");
        rbNoAvailability.setEnabled(false);

        btnsave.setBackground(new java.awt.Color(255, 255, 153));
        btnsave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 255, 153));
        btnupdate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btngoback.setBackground(new java.awt.Color(255, 255, 153));
        btngoback.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btngoback.setText("<<GO BACK");
        btngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmxseat, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmnseat, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel11)
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbYesAvailability)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNoAvailability))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbYesMaintainance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNoMaintainance))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtserailrnum, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtYmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnupdate)
                        .addGap(53, 53, 53)
                        .addComponent(btngoback)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbrand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtYmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtmodno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtmnseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbYesMaintainance)
                            .addComponent(rbNoMaintainance)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtmxseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(rbYesAvailability)
                                .addComponent(rbNoAvailability))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtserailrnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngoback, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlcolor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlcolor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmnseatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnseatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmnseatActionPerformed

    private void rbYesMaintainanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYesMaintainanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbYesMaintainanceActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        txtbrand2.setEnabled(true);
        txtcity.setEnabled(true);
        txtmxseat.setEnabled(true);
        txtmnseat.setEnabled(true);
        txtmodno.setEnabled(true);
        txtserailrnum.setEnabled(true);
        txtYmanufact.setEnabled(true);
        rbNoAvailability.setEnabled(true);
        rbNoMaintainance.setEnabled(true);
        rbYesAvailability.setEnabled(true);
        rbYesMaintainance.setEnabled(true);
        btnupdate.setEnabled(false);
        btnsave.setEnabled(true);
         populateCarDetails();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:        
        try{
            
            if(txtbrand2.getText().equals("") || txtcity.getText().equals("") || txtmodno.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Enter a value");
            
            else{
        c.setBrand(txtbrand2.getText());
        c.setManufacture(Integer.parseInt(txtYmanufact.getText()));
        c.setCityAvailable(txtcity.getText());
        c.setMaxseats(Integer.parseInt(txtmxseat.getText()));
        c.setMinseats(Integer.parseInt(txtmnseat.getText()));
        if(rbNoAvailability.isSelected()==true)
            c.setAvailable(false);
        if(rbYesAvailability.isSelected()==true)
            c.setAvailable(true);
        if(rbNoMaintainance.isSelected()==true)
            c.setMaintcert(false);
        if(rbYesMaintainance.isSelected()==true)
            c.setMaintcert(true);
        c.setModnumber(txtmodno.getText());
        c.setSrnumber(Integer.parseInt(txtserailrnum.getText()));
        populateTable();
        JOptionPane.showMessageDialog(null,"Car details are updated");
        btnupdate.setEnabled(true);
        btnsave.setEnabled(false);
         txtbrand2.setEnabled(false);
        txtcity.setEnabled(false);
        txtmxseat.setEnabled(false);
        txtmnseat.setEnabled(false);
        txtmodno.setEnabled(false);
        txtserailrnum.setEnabled(false);
        txtYmanufact.setEnabled(false);
        rbNoAvailability.setEnabled(false);
        rbNoMaintainance.setEnabled(false);
        rbYesAvailability.setEnabled(false);
        rbYesMaintainance.setEnabled(false);
        date =new Date();
        long Timme = date.getTime();
        timestamp= new Timestamp(Timme);
        Time= String.valueOf(timestamp);        
        lblTime.setText(Time);                
            }        
        }
catch(NumberFormatException c){JOptionPane.showMessageDialog(null, "Enter correct detail");}
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngobackActionPerformed
        // TODO add your handling code here:
        ProcCont.remove(this);
           CardLayout layout = (CardLayout) ProcCont.getLayout();
           layout.previous(ProcCont);        
    }//GEN-LAST:event_btngobackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngoback;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblred;
    private javax.swing.JPanel pnlcolor1;
    private javax.swing.JPanel pnlcolor2;
    private javax.swing.JRadioButton rbNoAvailability;
    private javax.swing.JRadioButton rbNoMaintainance;
    private javax.swing.JRadioButton rbYesAvailability;
    private javax.swing.JRadioButton rbYesMaintainance;
    private javax.swing.JTable tbldisplay;
    private javax.swing.JTextField txtYmanufact;
    private javax.swing.JTextField txtbrand2;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtmnseat;
    private javax.swing.JTextField txtmodno;
    private javax.swing.JTextField txtmxseat;
    private javax.swing.JTextField txtserailrnum;
    // End of variables declaration//GEN-END:variables
}
